# Load .bashrc
if [ -f /etc/bashrc ];then
    source /etc/bashrc
fi

if [ -f ~/.bashrc ];then
    source ~/.bashrc
fi

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# vim:ts=4:sw=4 syntax=bash
