set nocompatible

" TAB関連
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab

set bs=2

"表示系
syntax on
highlight Comment ctermfg=DarkCyan
colorscheme delek
set title
set showmatch
set wrap
set wildmenu
set showcmd
set list
set number
set scrolloff=5
set ruler
set ambiwidth=double

"文字コード系
set ffs=unix
set encoding=utf-8
set fileencoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,ucs-bom,iso-2022-jp,ucs2le,ucs-2,cp932,euc-jp
set fileformats=unix
set backspace=indent,eol,start

"入力支援
filetype on
filetype indent on
filetype plugin on
set autoindent
set smartindent
set laststatus=2
"set foldmethod=syntax
set listchars=tab:>\ ,extends:<

"検索
set incsearch
set hlsearch

set formatoptions+=m

autocmd BufRead,BufNewFile *.tsv set noexpandtab
autocmd BufRead,BufNewFile Makefile set noexpandtab
