## Environment Variable
export LC_LANG=ja_JP.UTF-8
export LANG=ja_JP.UTF-8
export EDITOR=/usr/local/bin/vim
export GIT_SSH=/usr/bin/ssh
export JAVA_HOME=$(/usr/libexec/java_home -v 11)

export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/gpg-agent/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/current/bin:/usr/local/Cellar/ruby/current/bin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:/usr/share/man"

# vim:ts=4:sw=4 syntax=zsh
